version: "3.3"

services:
  listener:
    image: k8tems/kinokonow_listener
    environment:
      - PYTHONUNBUFFERED=0
    entrypoint:
      sleep 1000
    secrets:
      - yahoo_api_key

secrets:
  yahoo_api_key:
    file: secrets/yahoo_api_key
