version: "3.3"

services:
  listener:
    image: kinokonow_listener
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ${FOLLOW_DIR}:/usr/src/app/follow.txt
    network_mode: host
    secrets:
      - yahoo_api_key

secrets:
  yahoo_api_key:
    external: true
