version: "3.3"

services:
  listener:
    image: k8tems/kinokonow_listener
    environment:
      - PYTHONUNBUFFERED=0
    entrypoint:
      sleep 1000000
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo

  redis:
    image: redis
