version: "3.3"

services:
  beat:
    image: k8tems/kinokonow_beat
    environment:
      - PYTHONUNBUFFERED=0
    depends_on:
      - redis

  worker:
    image: k8tems/kinokonow_worker
    environment:
      - PYTHONUNBUFFERED=0
    depends_on:
      - mongo
      - redis

  redis:
    image: redis

  mongo:
    image: mongo
    volumes:
      - /usr/share/kinokonow/mongo:/data/db
