version: "3.3"

services:
  beat:
    image: k8tems/kinokonow_expl_beat
    environment:
      - PYTHONUNBUFFERED=0
    depends_on:
      - redis

  worker:
    image: k8tems/kinokonow_expl_worker
    environment:
      - PYTHONUNBUFFERED=0
    depends_on:
      - redis

  redis:
    image: redis
