version: "3.3"

services:
  listener:
    image: k8tems/kinokonow_listener
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ../secrets/yahoo_api_key:/usr/src/app/yahoo_api_key
      - ../secrets/twitter.yml:/usr/src/app/twitter.yml
      - ../follow.txt:/usr/src/app/follow.txt
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo

  redis:
    image: redis
