version: "3.3"

services:
  listener:
    image: k8tems/kinokonow_listener
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./secrets/yahoo_api_key:/usr/src/app/yahoo_api_key
    entrypoint:
      cat /usr/src/app/yahoo_api_key
    depends_on:
      - mongo
      - redis

  worker:
    image: k8tems/kinokonow_worker
    environment:
      - PYTHONUNBUFFERED=0
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo

  redis:
    image: redis
