version: "3.3"

services:
  worker:
    image: k8tems/kinokonow_worker
    environment:
      - PYTHONUNBUFFERED=0
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo

  redis:
    image: redis

secrets:
  yahoo_api_key:
    file: secrets/yahoo_api_key
  twitter_key:
    file: secrets/twitter.yml

configs:
  follows:
    file: follow.txt
